# Generated by Django 5.2.17 on 2026-08-10 19:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('proposed', 'Proposée'), ('confirmed', 'Confirmée'), ('waitlisted', "Liste d'attente"), ('declined', 'Déclinée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='statut')),
                ('source', models.CharField(choices=[('admin', 'Secrétariat'), ('web', 'Site web'), ('participant', 'Portail participant'), ('trainer', 'Portail formateurs'), ('renewal', 'Reconduction'), ('import', 'Migration Welante')], default='admin', max_length=20, verbose_name='source')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Remplace le prix calculé, rabais compris.', max_digits=8, null=True, verbose_name='prix imposé (CHF)')),
                ('discount_override', models.DecimalField(blank=True, decimal_places=2, help_text='Promotion ou geste commercial. Prime sur le rabais automatique.', max_digits=5, null=True, verbose_name='rabais accordé (%)')),
                ('enrolled_on', models.DateField(default=datetime.date.today, verbose_name="date d'inscription")),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmée le')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulée le')),
                ('cancellation_reason', models.CharField(blank=True, max_length=200, verbose_name='motif')),
                ('notes', models.TextField(blank=True, verbose_name='remarques')),
                ('legacy_reference', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='référence Welante')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('billing_contact', models.ForeignKey(blank=True, help_text='Employeur, proche ou institution qui règle la facture. Vide : le participant est facturé lui-même.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billed_enrolments', to='contacts.contact', verbose_name='contact de facturation')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='catalog.course', verbose_name='cours')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='contacts.contact', verbose_name='participant')),
                ('renewed_from', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_to', to='enrolments.enrolment', verbose_name='reconduction de')),
            ],
            options={
                'verbose_name': 'inscription',
                'verbose_name_plural': 'inscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', 'status'], name='inscription_cours_statut'), models.Index(fields=['participant', 'status'], name='inscription_contact_statut')],
                'constraints': [models.UniqueConstraint(fields=('course', 'participant'), name='inscription_unique_par_cours'), models.CheckConstraint(condition=models.Q(('discount_override__isnull', True), models.Q(('discount_override__gte', 0), ('discount_override__lte', 100)), _connector='OR'), name='rabais_inscription_entre_0_et_100'), models.CheckConstraint(condition=models.Q(('price_override__isnull', True), ('price_override__gte', 0), _connector='OR'), name='prix_impose_positif')],
            },
        ),
    ]
