# Generated by Django 5.2.17 on 2026-08-10 19:32

import apps.core.fields
import apps.core.models
import apps.core.validators
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # Les contraintes d'exclusion de ce module reposent sur btree_gist :
        # l'extension doit exister avant que la contrainte ne soit posée.
        ("core", "0002_btree_gist"),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='identifiant')),
                ('name_fr', models.CharField(max_length=120, verbose_name='nom (FR)')),
                ('name_de', models.CharField(blank=True, max_length=120, verbose_name='nom (DE)')),
            ],
            options={
                'verbose_name': 'groupe de contacts',
                'verbose_name_plural': 'groupes de contacts',
                'ordering': ['name_fr'],
            },
            bases=(apps.core.models.TranslatedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('street', models.CharField(blank=True, max_length=120, verbose_name='rue')),
                ('house_number', models.CharField(blank=True, max_length=20, verbose_name='numéro')),
                ('address_complement', models.CharField(blank=True, max_length=120, verbose_name="complément d'adresse")),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='NPA')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='localité')),
                ('country', models.CharField(default='CH', max_length=2, verbose_name='pays')),
                ('salutation', models.CharField(choices=[('madam', 'Madame'), ('sir', 'Monsieur'), ('neutral', 'Sans civilité')], default='neutral', max_length=10, verbose_name='civilité')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='nom')),
                ('organisation', models.CharField(blank=True, max_length=200, verbose_name='organisation')),
                ('correspondence_language', models.CharField(choices=[('fr', 'FR'), ('de', 'DE')], default='fr', help_text='Toute communication sortante part dans cette langue.', max_length=2, verbose_name='langue de correspondance')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='courriel')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='mobile')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('is_collaborator', models.BooleanField(default=False, help_text="Ouvre droit au rabais collaborateur, sans être un type d'adhésion.", verbose_name='collaborateur/trice')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archivé')),
                ('legacy_notes', models.TextField(blank=True, help_text='Journal repris de Welante, en lecture seule. Les nouvelles notes sont horodatées et attribuées à leur auteur.', verbose_name='notes historiques (Welante)')),
                ('legacy_reference', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='référence Welante')),
                ('groups', models.ManyToManyField(blank=True, related_name='contacts', to='contacts.contactgroup', verbose_name='groupes')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ['last_name', 'first_name', 'organisation'],
            },
        ),
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('body', models.TextField(verbose_name='note')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_notes', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact', verbose_name='contact')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='code')),
                ('name_fr', models.CharField(max_length=120, verbose_name='nom (FR)')),
                ('name_de', models.CharField(blank=True, max_length=120, verbose_name='nom (DE)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Appliqué au prix de base, sauf sur les cours intensifs.', max_digits=5, verbose_name='rabais (%)')),
                ('annual_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='cotisation annuelle (CHF)')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': "type d'adhésion",
                'verbose_name_plural': "types d'adhésion",
                'ordering': ['discount_percent', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='rabais_entre_0_et_100')],
            },
            bases=(apps.core.models.TranslatedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('starts_on', models.DateField(verbose_name='début')),
                ('ends_on', models.DateField(blank=True, help_text='Vide : adhésion en cours.', null=True, verbose_name='fin')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='contacts.contact', verbose_name='contact')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='contacts.membershiptype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'adhésion',
                'verbose_name_plural': 'adhésions',
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('biography_fr', models.TextField(blank=True, verbose_name='présentation (FR)')),
                ('biography_de', models.TextField(blank=True, verbose_name='présentation (DE)')),
                ('iban', models.CharField(blank=True, max_length=34, validators=[apps.core.validators.validate_iban], verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('bank_name', models.CharField(blank=True, max_length=120, verbose_name='banque')),
                ('ahv_number', apps.core.fields.EncryptedTextField(blank=True, help_text='Donnée sensible (nLPD) : chiffrée au repos, réservée au rôle administration-comptabilité et exclue des exports par défaut.', verbose_name='no AVS')),
                ('ahv_waiver', models.BooleanField(default=False, help_text='La personne a renoncé aux cotisations AVS sur ces honoraires.', verbose_name='renonciation AVS')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trainer', to='contacts.contact', verbose_name='contact')),
            ],
            options={
                'verbose_name': 'formateur/formatrice',
                'verbose_name_plural': 'formateurs et formatrices',
                'ordering': ['contact__last_name', 'contact__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['last_name'], name='contact_nom_trigram', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['email'], name='contact_email_trigram', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['postal_code'], name='contact_npa'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('last_name', ''), _negated=True), models.Q(('organisation', ''), _negated=True), _connector='OR'), name='contact_a_un_nom_ou_une_organisation', violation_error_message='Un contact doit avoir au moins un nom de famille ou une organisation.'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gt', models.F('starts_on')), _connector='OR'), name='adhesion_finit_apres_son_debut'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(models.F('contact'), '='), (models.Func(models.F('starts_on'), models.F('ends_on'), models.Value('[)'), function='daterange', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='adhesions_sans_chevauchement', violation_error_message='Ce contact a déjà une adhésion couvrant cette période.'),
        ),
    ]
