# Generated by Django 5.2.17 on 2026-08-10 19:32

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='identifiant')),
                ('name_fr', models.CharField(max_length=150, verbose_name='nom (FR)')),
                ('name_de', models.CharField(blank=True, max_length=150, verbose_name='nom (DE)')),
                ('channel', models.CharField(choices=[('email', 'Courriel'), ('postal', 'Courrier postal')], default='email', max_length=20, verbose_name='canal')),
                ('scheduled_for', models.DateField(blank=True, null=True, verbose_name='prévu le')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyé le')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='catalog.period', verbose_name='période')),
            ],
            options={
                'verbose_name': 'campagne',
                'verbose_name_plural': 'campagnes',
                'ordering': ['-scheduled_for', '-created_at'],
            },
            bases=(apps.core.models.TranslatedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MailingDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('language', models.CharField(max_length=2, verbose_name="langue d'envoi")),
                ('status', models.CharField(choices=[('pending', 'À envoyer'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('skipped', 'Ignoré')], default='pending', max_length=20, verbose_name='statut')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyé le')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name="motif d'échec")),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='communications.mailingcampaign', verbose_name='campagne')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='contacts.contact', verbose_name='contact')),
            ],
            options={
                'verbose_name': 'envoi',
                'verbose_name_plural': 'envois',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'contact'), name='un_envoi_par_contact_et_campagne')],
            },
        ),
    ]
