# Generated by Django 5.2.17 on 2026-08-10 19:32

import apps.core.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        # Contrainte d'exclusion sur les séances : voir apps/core/migrations/0002.
        ('core', '0002_btree_gist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='code')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name="identifiant d'URL")),
                ('name_fr', models.CharField(max_length=80, verbose_name='nom (FR)')),
                ('name_de', models.CharField(blank=True, max_length=80, verbose_name='nom (DE)')),
                ('main_city', models.CharField(blank=True, max_length=80, verbose_name='ville principale')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'région',
                'verbose_name_plural': 'régions',
                'ordering': ['position', 'code'],
            },
            bases=(apps.core.models.TranslatedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('year', models.PositiveSmallIntegerField(verbose_name='année')),
                ('kind', models.CharField(choices=[('T1', '1er trimestre'), ('T2', '2e trimestre'), ('T3', '3e trimestre'), ('T4', '4e trimestre'), ('S1', '1er semestre'), ('S2', '2e semestre')], max_length=2, verbose_name='période')),
                ('starts_on', models.DateField(verbose_name='début')),
                ('ends_on', models.DateField(verbose_name='fin')),
                ('is_open_for_enrolment', models.BooleanField(default=False, verbose_name='inscriptions ouvertes')),
            ],
            options={
                'verbose_name': 'période',
                'verbose_name_plural': 'périodes',
                'ordering': ['-starts_on'],
                'constraints': [models.UniqueConstraint(fields=('year', 'kind'), name='periode_unique_par_annee'), models.CheckConstraint(condition=models.Q(('ends_on__gt', models.F('starts_on'))), name='periode_finit_apres_son_debut')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('street', models.CharField(blank=True, max_length=120, verbose_name='rue')),
                ('house_number', models.CharField(blank=True, max_length=20, verbose_name='numéro')),
                ('address_complement', models.CharField(blank=True, max_length=120, verbose_name="complément d'adresse")),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='NPA')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='localité')),
                ('country', models.CharField(default='CH', max_length=2, verbose_name='pays')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('access_notes_fr', models.TextField(blank=True, verbose_name='accès (FR)')),
                ('access_notes_de', models.TextField(blank=True, verbose_name='accès (DE)')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='catalog.region', verbose_name='région')),
            ],
            options={
                'verbose_name': 'lieu',
                'verbose_name_plural': 'lieux',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(help_text='Format : AAAA-Px-NNNNNN[v]-RG. Les codes hérités sont acceptés.', max_length=40, unique=True, verbose_name='code')),
                ('title_fr', models.CharField(max_length=200, verbose_name='titre (FR)')),
                ('title_de', models.CharField(blank=True, max_length=200, verbose_name='titre (DE)')),
                ('summary_fr', models.TextField(blank=True, verbose_name='accroche (FR)')),
                ('summary_de', models.TextField(blank=True, verbose_name='accroche (DE)')),
                ('description_fr', models.TextField(blank=True, verbose_name='descriptif (FR)')),
                ('description_de', models.TextField(blank=True, verbose_name='descriptif (DE)')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix de base (CHF)')),
                ('is_intensive', models.BooleanField(default=False, help_text='Neutralise tous les rabais membres et collaborateurs.', verbose_name='cours intensif')),
                ('min_participants', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='minimum')),
                ('max_participants', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maximum')),
                ('administrative_type', models.CharField(choices=[('standard', 'Cours au programme'), ('ors', 'ORS (intégration)'), ('internal', 'Formation interne'), ('corporate', 'Cours privés et entreprises')], default='standard', max_length=20, verbose_name='type administratif')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='draft', max_length=20, verbose_name='statut')),
                ('in_newsletter', models.BooleanField(default=False, verbose_name='dans la newsletter')),
                ('is_highlight', models.BooleanField(default=False, verbose_name='coup de cœur')),
                ('has_guaranteed_start', models.BooleanField(default=False, verbose_name='démarrage garanti')),
                ('is_on_demand', models.BooleanField(default=False, verbose_name='sur demande')),
                ('legacy_reference', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='référence Welante')),
                ('continues', models.ForeignKey(blank=True, help_text="Cours de la période précédente dont celui-ci prend la suite. C'est ce lien qui permet de proposer la reconduction aux inscrits.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continued_by', to='catalog.course', verbose_name='suite du cours')),
                ('trainers', models.ManyToManyField(blank=True, related_name='courses', to='contacts.trainer', verbose_name='formateurs')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='catalog.period', verbose_name='période')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='catalog.region', verbose_name='région')),
            ],
            options={
                'verbose_name': 'cours',
                'verbose_name_plural': 'cours',
                'ordering': ['-period__starts_on', 'code'],
            },
            bases=(apps.core.models.TranslatedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=100, verbose_name='salle')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='capacité')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='catalog.location', verbose_name='lieu')),
            ],
            options={
                'verbose_name': 'salle',
                'verbose_name_plural': 'salles',
                'ordering': ['location__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('starts_at', models.DateTimeField(verbose_name='début')),
                ('ends_at', models.DateTimeField(verbose_name='fin')),
                ('status', models.CharField(choices=[('scheduled', 'Prévue'), ('cancelled', 'Annulée')], default='scheduled', max_length=20, verbose_name='statut')),
                ('cancellation_reason', models.CharField(blank=True, max_length=200, verbose_name="motif d'annulation")),
                ('note_fr', models.CharField(blank=True, max_length=200, verbose_name='remarque (FR)')),
                ('note_de', models.CharField(blank=True, max_length=200, verbose_name='remarque (DE)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='catalog.course', verbose_name='cours')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='catalog.room', verbose_name='salle')),
            ],
            options={
                'verbose_name': 'séance',
                'verbose_name_plural': 'séances',
                'ordering': ['starts_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='default_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='catalog.room', verbose_name='salle habituelle'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Web-Code')),
                ('name_fr', models.CharField(max_length=120, verbose_name='nom (FR)')),
                ('name_de', models.CharField(blank=True, max_length=120, verbose_name='nom (DE)')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.subject', verbose_name='matière parente')),
            ],
            options={
                'verbose_name': 'matière',
                'verbose_name_plural': 'matières',
                'ordering': ['position', 'name_fr'],
            },
            bases=(apps.core.models.TranslatedFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='courses', to='catalog.subject', verbose_name='matières'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('day', models.DateField(verbose_name='date')),
                ('name_fr', models.CharField(max_length=120, verbose_name='nom (FR)')),
                ('name_de', models.CharField(blank=True, max_length=120, verbose_name='nom (DE)')),
                ('region', models.ForeignKey(blank=True, help_text='Vide : férié dans tout le canton.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='catalog.region', verbose_name='région')),
            ],
            options={
                'verbose_name': 'jour férié',
                'verbose_name_plural': 'jours fériés',
                'ordering': ['day'],
                'constraints': [models.UniqueConstraint(fields=('day', 'region'), name='ferie_unique_par_region')],
            },
            bases=(apps.core.models.TranslatedFieldsMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='salle_unique_par_lieu'),
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['course', 'starts_at'], name='seance_cours_debut'),
        ),
        migrations.AddConstraint(
            model_name='coursesession',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='seance_finit_apres_son_debut'),
        ),
        migrations.AddConstraint(
            model_name='coursesession',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('room__isnull', False), ('status', 'scheduled')), expressions=[(models.F('room'), '='), (models.Func(models.F('starts_at'), models.F('ends_at'), models.Value('[)'), function='tstzrange', output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField()), '&&')], name='salle_sans_double_reservation', violation_error_message='Cette salle est déjà occupée sur ce créneau.'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'region'], name='cours_statut_region'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('min_participants__isnull', True), ('max_participants__isnull', True), ('max_participants__gte', models.F('min_participants')), _connector='OR'), name='cours_maximum_superieur_au_minimum'),
        ),
    ]
