# Generated by Django 5.2.17 on 2026-08-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title_de',
            field=models.CharField(blank=True, max_length=400, verbose_name='titre (DE)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_fr',
            field=models.CharField(max_length=400, verbose_name='titre (FR)'),
        ),
    ]
